# ===================================================================
# 日志与调试配置
# ===================================================================
logging.file.name=logs/${spring.application.name}.log
logging.level.cn.caldm.www=debug
logging.level.org.apache.ibatis=debug
spring.output.ansi.enabled=ALWAYS