server.port=14040
# server.servlet.context-path=/api

# ===================================================================
# 日志与调试配置
# ===================================================================
logging.file.name=logs/${spring.application.name}.log
logging.level.cn.caldm.www=debug
logging.level.org.apache.ibatis=debug
spring.output.ansi.enabled=ALWAYS

spring.datasource.url=jdbc:mysql://localhost:3306/study?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=你的MySQL密码
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false

management.endpoints.web.exposure.include=*
