server.port=14040
server.servlet.context-path=/api

# ===================================================================
# 日志与调试配置
# ===================================================================
logging.file.name=logs/${spring.application.name}.log
logging.level.cn.caldm.www=debug
logging.level.org.apache.ibatis=debug
spring.output.ansi.enabled=ALWAYS

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.thymeleaf.cache=false

management.endpoints.web.exposure.include=*
